GET http://127.0.0.1:8000/fetchWorks/ 
content-type: application/json
Authorization: Token 390d4c697c68f8b3ff992b7c4fdb279244d935df

# {
    
#     "uid" : 238,
#     "username": "akash",
#     "msg" :  "Come soon",
#     "lat" : 10.54875630,
#     "lon" : 27.54465656565
# }
